name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Release Environment Variables
      if: startsWith(github.ref, 'refs/heads/release-')
      run: |
        echo "::set-env name=CREATE_RELEASE::true"
        echo "::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF##*/release-})"
        echo "::set-env name=VERSION::${RELEASE_VERSION}.${GITHUB_RUN_ID}"

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build

    - name: Package
      if: env.CREATE_RELEASE == 'true'
      run: |
        dotnet pack ./src/Debugosaurus.BigUnits/Debugosaurus.BigUnits.csproj --configuration Release --no-build -p:Version=$VERSION -p:PackageVersion=$VERSION -p:RepositoryUrl=https://github.com/debugosaurus/BigUnits
        dotnet pack ./src/Debugosaurus.BigUnits.Moq/Debugosaurus.BigUnits.Moq.csproj --configuration Release --no-build -p:Version=$VERSION -p:PackageVersion=$VERSION -p:RepositoryUrl=https://github.com/debugosaurus/BigUnits
    - name: Publish
      if: env.CREATE_RELEASE == 'true'
      run: |
        dotnet nuget push "./src/Debugosaurus.BigUnits/bin/Release/BigUnits.$VERSION.nupkg" -k ${{ secrets.NUGET_DOT_ORG_PUBLISH_KEY }} -s https://api.nuget.org/v3/index.json
        dotnet nuget push "./src/Debugosaurus.BigUnits.Moq/bin/Release/BigUnits.Moq.$VERSION.nupkg" -k ${{ secrets.NUGET_DOT_ORG_PUBLISH_KEY }} -s https://api.nuget.org/v3/index.json