name: .NET Core

env:
  VERSION: 0.0.1

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Package
      if: contains(github.ref, 'master')
      run: |
        dotnet pack ./src/Debugosaurus.BigUnits/Debugosaurus.BigUnits.csproj --configuration Release --no-build -p:Version=$VERSION -p:PackageVersion=$VERSION -p:RepositoryUrl=https://github.com/debugosaurus/BigUnits
        dotnet pack ./src/Debugosaurus.BigUnits.Moq/Debugosaurus.BigUnits.Moq.csproj --configuration Release --no-build -p:Version=$VERSION -p:PackageVersion=$VERSION -p:RepositoryUrl=https://github.com/debugosaurus/BigUnits
    - name: Publish
      if: contains(github.ref, 'master')
      run: |
        dotnet nuget push "./src/Debugosaurus.BigUnits/bin/Release/Debugosaurus.BigUnits.$VERSION.nupkg" -k ${{ secrets.NUGET_DOT_ORG_PUBLISH_KEY }} -s https://api.nuget.org/v3/index.json
        dotnet nuget push "./src/Debugosaurus.BigUnits.Moq/bin/Release/Debugosaurus.BigUnits.Moq.$VERSION.nupkg" -k ${{ secrets.NUGET_DOT_ORG_PUBLISH_KEY }} -s https://api.nuget.org/v3/index.json